### ISSUE TITLE
Error with custom endpoint (storj.io)

### ISSUE THREAD

**Issue by danielchicote** [thaiphan/magento-s3#32]
Hello, i'm trying to use storj.io as S3 service, but magento (openmage) always gets the images from the local folder and exception.log gives me this error:

`2023-04-04T13:18:01+00:00 ERR (3): 
Zend_Uri_Exception: Illegal scheme supplied, only alphanumeric characters are permitted in C:\Server\www\openmage\lib\Zend\Uri.php:111
Stack trace:
#0 C:\Server\www\openmage\lib\Zend\Service\Amazon\S3.php(79): Zend_Uri::factory(Array)
#1 C:\Server\www\openmage\app\code\community\Thai\S3\Helper\Data.php(20): Zend_Service_Amazon_S3->setEndpoint('media.gateway.s...')
#2 C:\Server\www\openmage\app\code\community\Thai\S3\Model\Resource\Core\File\Storage\S3.php(16): Thai_S3_Helper_Data->getClient()
#3 C:\Server\www\openmage\app\code\core\Mage\Core\Helper\File\Storage\Database.php(231): Thai_S3_Model_Resource_Core_File_Storage_S3->deleteFolder('catalog/product...')
#4 C:\Server\www\openmage\app\code\core\Mage\Catalog\Model\Product\Image.php(772): Mage_Core_Helper_File_Storage_Database->deleteFolder('C:\\Server\\www\\o...')
#5 C:\Server\www\openmage\app\code\core\Mage\Adminhtml\controllers\CacheController.php(173): Mage_Catalog_Model_Product_Image->clearCache()
#6 C:\Server\www\openmage\app\code\core\Mage\Core\Controller\Varien\Action.php(429): Mage_Adminhtml_CacheController->cleanImagesAction()
#7 C:\Server\www\openmage\app\code\core\Mage\Core\Controller\Varien\Router\Standard.php(256): Mage_Core_Controller_Varien_Action->dispatch('cleanImages')
#8 C:\Server\www\openmage\app\code\core\Mage\Core\Controller\Varien\Front.php(190): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#9 C:\Server\www\openmage\app\code\core\Mage\Core\Model\App.php(373): Mage_Core_Controller_Varien_Front->dispatch()
#10 C:\Server\www\openmage\app\Mage.php(734): Mage_Core_Model_App->run(Array)
#11 C:\Server\www\openmage\index.php(82): Mage::run('', 'store')
#12 {main}
`
This is my config:
![Screenshot 2023-04-04 at 15-56-43 Configuration _ System _ OpenMage Admin](https://user-images.githubusercontent.com/7643167/229816148-20339413-183e-4304-b54a-94d08a63f447.png)

And don't know what it means, i have enabled S3 from the shell script, clean caches, and the uri that gets the error appers to be correct. Can someone help with this?

**Comment by colinmollenhour** [comment]
Add 'https://' to the Custom Endpoint
